### PR TITLE
Fix taglist extension

### PR DESCRIPTION
**Pull request by demonicblue**
Make compatible with sphinx 1.8.0

### CODE REVIEW

**Comment by sashko** [comment]
Are we gonna upgrade sphinx to 1.8.x on our Docker image? Does it break compatibility with the currently used version?

**Comment by demonicblue** [comment]
I would expect this extension to work with both 1.7.x and 1.8.x but the failed integration build says otherwise :(

**Comment by thenor** [comment]
@demonicblue It seems to be a spelling error, so nothing serious.
"[Blueprint] Found 1 misspelled words"
We don't have a way to check where the error is from Jenkins, but if you build locally can you see the spelling error?

**Review by thenor — APPROVED** [review]
From what I can see the spelling error is from a previous merge (I'm looking at you @sashko :P).

**Review by sashko — APPROVED** [review]
Therese has tested it and confirmed it works on older versions as well; Jenkins build has failed due to a different issue. Feel free to merge it.

**Pull request merged**
