### PR TITLE
architecture: Capitalize subtitles

### PR DESCRIPTION
**Pull request by GordanM**
Signed-off-by: Gordan Markuš <gordan.markus@pelagicore.com>

### CODE REVIEW

**Comment by tobsan** [comment]
Is this the way it is done in most other chapters? If so, go ahead (but I think it is actually bad style). If not, we should keep the existing style.

**Review by breakreturn — CHANGES_REQUESTED** [review]
This is not how it's done in general in the SWF docs.

**Comment by GordanM** [comment]
Yup, just checked it. The arc42 template confused me as they do it this way. I'll use this PR to fix the caps on all the Architecture related chapters.

**Comment by GordanM** [comment]
Updated @breakreturn and @tobsan .

**Review by tobsan — APPROVED** [review]

**Review by breakreturn — APPROVED** [review]

**Pull request merged**
