### PR TITLE
Use autosectionlabel extension

### PR DESCRIPTION
**Pull request by tobsan**
Instead of manually creating labels, the autosectionlabel extension
creates labels from each header in the documentation.

Signed-off-by: Tobias Olausson <tobias.olausson@pelagicore.com>

### CODE REVIEW

**Review by DunderRoffe — COMMENTED** [review]
It is a bit weird to not be able to have two headings with the same name in different chapters for instance "Introduction".

Can not decide if this is good or bad... 
I kinda like the forced verbosity. Although it is really bad from a layout perspective.

**Comment by tobsan** [comment]
@DunderRoffe it is possible if we add the extra flag that the ref has to be prepended with document name.

**Comment by demonicblue** [comment]
If we prepend refs with document names, doesn't that defeat the purpose of references being decoupled from document names and paths?

**Comment by tobsan** [comment]
@demonicblue yeah, it kinda does. Well not paths, but document names for sure.

**Comment by tobsan** [comment]
@dunderroffe @demonicblue should I interpret this discussion as if we don't want autosectionlabel?

**Comment by DunderRoffe** [comment]
I would say so. Adding the labels are not that annoying anyway. It feels a bit sad although I guess it is better to keep it the way it is

**Pull request closed without merging**
